# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # Explicitly specify logging to Cloud Logging only

steps:
  # Step 1: Build the Docker image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--cache-from'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:latest'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:$COMMIT_SHA'

  # Step 3: Tag the image as "latest" for caching
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - artifacts
      - docker
      - tag
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:$COMMIT_SHA'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:latest'

  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - 'gcpbreadcalc'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'  # Replace with your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/gcpbreadcalc:$COMMIT_SHA'
