   # cloudbuild.yaml
   options:
     logging: CLOUD_LOGGING_ONLY

   steps:
     # Step 1: Pull the latest image for caching (if it exists)
     - name: 'gcr.io/cloud-builders/docker'
       args: ['pull', 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:latest']
       continueOnFail: true

     # Step 2: Build the Docker image with caching
     - name: 'gcr.io/cloud-builders/docker'
       args:
         - build
         - '--cache-from'
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:latest'
         - '-t'
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:$COMMIT_SHA'
         - '.'

     # Step 3: Push the Docker image with the new commit SHA
     - name: 'gcr.io/cloud-builders/docker'
       args:
         - push
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:$COMMIT_SHA'

     # Step 4: Tag the image as "latest"
     - name: 'gcr.io/cloud-builders/docker'
       args:
         - tag
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:$COMMIT_SHA'
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:latest'

     # Step 5: Push the "latest" tagged image
     - name: 'gcr.io/cloud-builders/docker'
       args:
         - push
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:latest'

     # Step 6: Deploy the Docker image to Cloud Run
     - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
       entrypoint: 'gcloud'
       args:
         - run
         - deploy
         - 'gcpbreadcalc'
         - '--image'
         - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:$COMMIT_SHA'
         - '--region'
         - 'europe-west1'
         - '--platform'
         - 'managed'
         - '--allow-unauthenticated'

   images:
     - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:$COMMIT_SHA'
     - 'gcr.io/$PROJECT_ID/github.com/drwitloof/gcpbreadcalc:latest'
